### ISSUE TITLE
“Manifest file invalid” in the Chrome Web Store

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [avelino/irccloud-chrome#1]
I'd like to install IRCcloud with this, but it's failing:

![image](https://f.cloud.github.com/assets/200/668869/36fe0c5a-d820-11e2-94a3-8582ebe1a53b.png)

**Comment by loganrosen** [comment]
I'm having the same issue in Chrome 29.0.1542.0 (Official Build 207120) canary on Windows.
